services:
  - type: web
    name: studybuddy
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn studybuddy.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
